### ISSUE TITLE
Can't use i18n inside Node Component

### ISSUE THREAD

**Issue by SilasNiewierra** [jerosoler/Drawflow#274]
Hi @jerosoler ,
I'm desperately trying to get vuei18n to work.
I have a simple workflow:

Editor.vue
```js
...
 // Register nodes
const nodeProps = (key) => ({
  step: stepTemplates[key],
  toggleDetails: this.toggleNodeDetails,
  editor: this.editor,
})

Object.keys(stepTemplates).forEach((key) => {
  this.editor.registerNode(key, Step, nodeProps(key))
})
...
```

Step.vue
```js
<template>
  <div class="header d-flex align-center">
    <img :src="step.icon" height="32" />
    <div class="ml-2 title text-h5 font-weight-medium">
      {{ $t(step.title) }}
    </div>
  </div>
  <div class="mt-4">
    <trigger-step
      :toggleDetails="toggleDetails"
      :editor="editor"
    />
  </div>
</template>
```

TriggerStep.vue
```js
<template>
  <div class="mt-4">
    <div class="d-flex">
      <p>{{ $t('steps.trigger.desc') }}</p>
      <div class="ml-1" @click="toggleDetails">
        <input
          class="dynamic-field"
          disabled
          :value="node.eventname"
          :placeholder="$t('steps.trigger.placeholderEventName')"
        />
      </div>
    </div>
  </div>
</template>
```

What I expected to happen:
The Step is displayed in the editor correctly with the string in the .json file.

What happens:
`TypeError: _ctx.$t is not a function
`

**Comment by jerosoler** [comment]
It works well. We can even pass drawflow as a globalProperties

Parent Node "drawflow.vue"
```javascript
 const internalInstance = getCurrentInstance()
   internalInstance.appContext.app._context.config.globalProperties.$df = editor;
```

Child component:
```javascript
<template>
 <div ref="el">Hi!</div>
 <input df-namevalue>
 <el-button type="primary" @click="getdata()">Button</el-button>
</template>

<script>
import { onMounted, ref, getCurrentInstance } from 'vue'



export default {

  setup() {
   
   const el = ref(null);
    const app = getCurrentInstance()
    const df = app.appContext.config.globalProperties.$df

    function getdata() {
      console.log(df._value.getNodeFromId(el.value.parentElement.parentElement.id.slice(5)));
    }

    onMounted(() => {
      console.log(el.value.parentElement.parentElement.id);
    });
    
    return {
      el, getdata
    }
  }
}
</script>

```

**Comment by SilasNiewierra** [comment]
I went inside the drawflow.js and fixed the errors manually, but am not sure if I broke something with it?

For now it seems to work, but instead of 
` editor.value = new Drawflow(id, Vue, internalInstance.appContext.app._context);`
I had to do 
` editor= new Drawflow(id, Vue, internalInstance.appContext.app._context);` 
or else I would get errors like `editor.on is not a function`

**Comment by jerosoler** [comment]
Drawflow project not a eslint. 

add in head of file: errors disable
```javascript
/*eslint-disable */
export default class Drawflow {
```

If you check that it works I will upload the changes to npm

**Comment by SilasNiewierra** [comment]
Cool, I will try it again 👍 
I'll give you an update in a second 😄

**Comment by SilasNiewierra** [comment]
One thing I just tested: 
When I set the mode to fixed, I was able to change the value inside the Node component. Now it throws an error if I try to do so?

**Comment by SilasNiewierra** [comment]
Okay I will try that as well. 
Maybe its a vuetify 3 alpha problem.

Thank you so much, this is amazing 😍 🎉 
If you upload it to npm, please let me know, so I can just install it and remove my local drawflow.js file 😄

**Comment by jerosoler** [comment]
This afternoon I'll upload it if I can!

**Comment by SilasNiewierra** [comment]
Hi @jerosoler ,
as I mentioned above, you need to change `html` to `dataNode.html` inside the `addNodeImport` adjustments.
Right now the library does not work with 0.0.5 😁
